export default [
  {
    title: 'Nr inwentarzowy',
    fieldName: 'symbol',
    draggable: true,
    sorting: true,
    position: 0,
  },
  {
    title: 'Id',
    fieldName: 'id',
    sorting: true,
    draggable: true,
    position: 1,
  },
  {
    title: 'Nazwa',
    fieldName: 'name',
    sorting: true,
    draggable: true,
    position: 2,
  },
  {
    title: 'Prawa autorskie',
    fieldName: 'copyright',
    sorting: true,
    draggable: true,
    position: 3,
  },
  {
    title: 'Znak',
    fieldName: 'sign',
    // sorting: true,
    draggable: true,
    position: 4,
  },
  {
    title: 'Data wypożyczenia',
    fieldName: 'rentFrom',
    sorting: true,
    draggable: true,
    position: 5,
  },
  {
    title: 'Data zwrotu',
    fieldName: 'rentTo',
    sorting: true,
    draggable: true,
    position: 6,
  },
  {
    title: 'Twórca/ wytwórnia',
    fieldName: 'author',
    draggable: true,
    position: 7,
  },
  {
    title: 'Materiał',
    fieldName: 'material',
    draggable: true,
    position: 8,
  },
  {
    title: 'Źródło nabycia',
    fieldName: 'source',
    draggable: true,
    position: 9,
  },
  {
    title: 'Uwagi',
    fieldName: 'comments',
    draggable: true,
    position: 9,
  },
  {
    title: 'Zwrócony',
    fieldName: 'isReturned',
    draggable: true,
    position: 10,
  },
  {
    title: '',
    fieldName: 'menu',
    draggable: false,
    position: 999,
  },
];
